export enum Environment {
  APP_ENV = 'APP_ENV',
  PORT = 'PORT',
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  JWT_SECRET = 'JWT_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
}
